// Cliente tipado de Data912 (data912.com / data912.apidocs.ar)
// Endpoints en vivo para CEDEARs, Acciones argentinas, Bonos y Mercado USA

export interface Data912QuoteRaw {
  symbol: string;
  c: number; // Último precio operado
  pct_change: number; // Variación porcentual diaria
  v?: number; // Volumen operado
  px_bid?: number; // Oferta de compra
  px_ask?: number; // Oferta de venta
  q_bid?: number;
  q_ask?: number;
  q_op?: number;
  t?: string; // Timestamp
}

const BASE_URL = "https://data912.com";

// Mapeo amigable de tickers a nombres completos e industrias.
// Muchas personas buscan por el nombre de la empresa, no por el ticker técnico
// (por eso la tabla y el buscador muestran ambos). BYMA opera cada CEDEAR y
// cada acción local bajo varios mecanismos de liquidación que comparten
// símbolo base: sin sufijo (pesos/CI), "C" (Cable/CCL) y "D" (Dólar MEP) para
// CEDEARs; "D" (o ".D") para acciones locales. Se listan las variantes más
// operadas explícitamente en vez de derivarlas para evitar asociaciones
// incorrectas con tickers que ya terminan en "C" o "D" por su cuenta.
export const ASSET_NAMES: Record<string, { nombre: string; entidad: string }> = {
  // ===== CEDEARs de empresas y ETFs de EE.UU. / globales =====
  SPY: { nombre: "CEDEAR SPDR S&P 500 ETF Trust", entidad: "State Street Global Advisors / BYMA" },
  QQQ: { nombre: "CEDEAR Invesco QQQ Trust (Nasdaq 100)", entidad: "Invesco / BYMA" },
  DIA: { nombre: "CEDEAR SPDR Dow Jones Industrial Average ETF", entidad: "State Street / BYMA" },
  DIAC: { nombre: "CEDEAR SPDR Dow Jones Industrial Average ETF (liq. Cable)", entidad: "State Street / BYMA" },
  DIAD: { nombre: "CEDEAR SPDR Dow Jones Industrial Average ETF (liq. Dólar MEP)", entidad: "State Street / BYMA" },
  ARKK: { nombre: "CEDEAR ARK Innovation ETF", entidad: "ARK Invest / BYMA" },
  ARKKC: { nombre: "CEDEAR ARK Innovation ETF (liq. Cable)", entidad: "ARK Invest / BYMA" },
  ARKKD: { nombre: "CEDEAR ARK Innovation ETF (liq. Dólar MEP)", entidad: "ARK Invest / BYMA" },
  ACWI: { nombre: "CEDEAR iShares MSCI ACWI ETF", entidad: "BlackRock / BYMA" },
  ACWIC: { nombre: "CEDEAR iShares MSCI ACWI ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  ACWID: { nombre: "CEDEAR iShares MSCI ACWI ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  EEM: { nombre: "CEDEAR iShares MSCI Emerging Markets ETF", entidad: "BlackRock / BYMA" },
  EEMC: { nombre: "CEDEAR iShares MSCI Emerging Markets ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  EEMD: { nombre: "CEDEAR iShares MSCI Emerging Markets ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  EFA: { nombre: "CEDEAR iShares MSCI EAFE ETF", entidad: "BlackRock / BYMA" },
  EFAC: { nombre: "CEDEAR iShares MSCI EAFE ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  EFAD: { nombre: "CEDEAR iShares MSCI EAFE ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  FXI: { nombre: "CEDEAR iShares China Large-Cap ETF", entidad: "BlackRock / BYMA" },
  FXIC: { nombre: "CEDEAR iShares China Large-Cap ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  FXID: { nombre: "CEDEAR iShares China Large-Cap ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  GDX: { nombre: "CEDEAR VanEck Gold Miners ETF", entidad: "VanEck / BYMA" },
  GDXC: { nombre: "CEDEAR VanEck Gold Miners ETF (liq. Cable)", entidad: "VanEck / BYMA" },
  GDXD: { nombre: "CEDEAR VanEck Gold Miners ETF (liq. Dólar MEP)", entidad: "VanEck / BYMA" },
  GLD: { nombre: "CEDEAR SPDR Gold Shares (Oro)", entidad: "State Street / BYMA" },
  GLDC: { nombre: "CEDEAR SPDR Gold Shares (Oro, liq. Cable)", entidad: "State Street / BYMA" },
  GLDD: { nombre: "CEDEAR SPDR Gold Shares (Oro, liq. Dólar MEP)", entidad: "State Street / BYMA" },
  IBB: { nombre: "CEDEAR iShares Biotechnology ETF", entidad: "BlackRock / BYMA" },
  IBBC: { nombre: "CEDEAR iShares Biotechnology ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  IBBD: { nombre: "CEDEAR iShares Biotechnology ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  IBIT: { nombre: "CEDEAR iShares Bitcoin Trust", entidad: "BlackRock / BYMA" },
  IBITC: { nombre: "CEDEAR iShares Bitcoin Trust (liq. Cable)", entidad: "BlackRock / BYMA" },
  IBITD: { nombre: "CEDEAR iShares Bitcoin Trust (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  ETHA: { nombre: "CEDEAR iShares Ethereum Trust", entidad: "BlackRock / BYMA" },
  ETHAC: { nombre: "CEDEAR iShares Ethereum Trust (liq. Cable)", entidad: "BlackRock / BYMA" },
  ETHAD: { nombre: "CEDEAR iShares Ethereum Trust (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  CIBR: { nombre: "CEDEAR First Trust Nasdaq Cybersecurity ETF", entidad: "First Trust / BYMA" },
  CIBRC: { nombre: "CEDEAR First Trust Nasdaq Cybersecurity ETF (liq. Cable)", entidad: "First Trust / BYMA" },
  CIBRD: { nombre: "CEDEAR First Trust Nasdaq Cybersecurity ETF (liq. Dólar MEP)", entidad: "First Trust / BYMA" },
  COPX: { nombre: "CEDEAR Global X Copper Miners ETF", entidad: "Global X / BYMA" },
  COPXC: { nombre: "CEDEAR Global X Copper Miners ETF (liq. Cable)", entidad: "Global X / BYMA" },
  COPXD: { nombre: "CEDEAR Global X Copper Miners ETF (liq. Dólar MEP)", entidad: "Global X / BYMA" },
  ICLN: { nombre: "CEDEAR iShares Global Clean Energy ETF", entidad: "BlackRock / BYMA" },
  ICLNC: { nombre: "CEDEAR iShares Global Clean Energy ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  EWJ: { nombre: "CEDEAR iShares MSCI Japan ETF", entidad: "BlackRock / BYMA" },
  EWJC: { nombre: "CEDEAR iShares MSCI Japan ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  EWJD: { nombre: "CEDEAR iShares MSCI Japan ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  EWY: { nombre: "CEDEAR iShares MSCI South Korea ETF", entidad: "BlackRock / BYMA" },
  EWYC: { nombre: "CEDEAR iShares MSCI South Korea ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  EWYD: { nombre: "CEDEAR iShares MSCI South Korea ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  EWZ: { nombre: "CEDEAR iShares MSCI Brazil ETF", entidad: "BlackRock / BYMA" },
  EWZC: { nombre: "CEDEAR iShares MSCI Brazil ETF (liq. Cable)", entidad: "BlackRock / BYMA" },
  EWZD: { nombre: "CEDEAR iShares MSCI Brazil ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },
  ESGU: { nombre: "CEDEAR iShares ESG Aware MSCI USA ETF", entidad: "BlackRock / BYMA" },
  ESGUD: { nombre: "CEDEAR iShares ESG Aware MSCI USA ETF (liq. Dólar MEP)", entidad: "BlackRock / BYMA" },

  AAPL: { nombre: "CEDEAR Apple Inc.", entidad: "Apple / BYMA" },
  AAPLC: { nombre: "CEDEAR Apple Inc. (liq. Cable)", entidad: "Apple / BYMA" },
  AAPLD: { nombre: "CEDEAR Apple Inc. (liq. Dólar MEP)", entidad: "Apple / BYMA" },
  MSFT: { nombre: "CEDEAR Microsoft Corporation", entidad: "Microsoft / BYMA" },
  NVDA: { nombre: "CEDEAR NVIDIA Corporation", entidad: "NVIDIA / BYMA" },
  NVDAC: { nombre: "CEDEAR NVIDIA Corporation (liq. Cable)", entidad: "NVIDIA / BYMA" },
  NVDAD: { nombre: "CEDEAR NVIDIA Corporation (liq. Dólar MEP)", entidad: "NVIDIA / BYMA" },
  AMZN: { nombre: "CEDEAR Amazon.com Inc.", entidad: "Amazon / BYMA" },
  AMZNC: { nombre: "CEDEAR Amazon.com Inc. (liq. Cable)", entidad: "Amazon / BYMA" },
  AMZND: { nombre: "CEDEAR Amazon.com Inc. (liq. Dólar MEP)", entidad: "Amazon / BYMA" },
  GOOGL: { nombre: "CEDEAR Alphabet Inc. Clase A (Google)", entidad: "Alphabet / BYMA" },
  META: { nombre: "CEDEAR Meta Platforms Inc.", entidad: "Meta / BYMA" },
  TSLA: { nombre: "CEDEAR Tesla Inc.", entidad: "Tesla / BYMA" },
  TSLAC: { nombre: "CEDEAR Tesla Inc. (liq. Cable)", entidad: "Tesla / BYMA" },
  TSLAD: { nombre: "CEDEAR Tesla Inc. (liq. Dólar MEP)", entidad: "Tesla / BYMA" },
  MELI: { nombre: "CEDEAR MercadoLibre Inc.", entidad: "MercadoLibre / BYMA" },
  KO: { nombre: "CEDEAR The Coca-Cola Company", entidad: "Coca-Cola / BYMA" },
  BRKB: { nombre: "CEDEAR Berkshire Hathaway Inc. Clase B", entidad: "Berkshire Hathaway / BYMA" },
  BRKBC: { nombre: "CEDEAR Berkshire Hathaway Inc. Clase B (liq. Cable)", entidad: "Berkshire Hathaway / BYMA" },
  BRKBD: { nombre: "CEDEAR Berkshire Hathaway Inc. Clase B (liq. Dólar MEP)", entidad: "Berkshire Hathaway / BYMA" },
  AAL: { nombre: "CEDEAR American Airlines Group", entidad: "American Airlines / BYMA" },
  AALC: { nombre: "CEDEAR American Airlines Group (liq. Cable)", entidad: "American Airlines / BYMA" },
  AALD: { nombre: "CEDEAR American Airlines Group (liq. Dólar MEP)", entidad: "American Airlines / BYMA" },
  ABBV: { nombre: "CEDEAR AbbVie Inc.", entidad: "AbbVie / BYMA" },
  ABBVC: { nombre: "CEDEAR AbbVie Inc. (liq. Cable)", entidad: "AbbVie / BYMA" },
  ABBVD: { nombre: "CEDEAR AbbVie Inc. (liq. Dólar MEP)", entidad: "AbbVie / BYMA" },
  ABNB: { nombre: "CEDEAR Airbnb Inc.", entidad: "Airbnb / BYMA" },
  ABNBC: { nombre: "CEDEAR Airbnb Inc. (liq. Cable)", entidad: "Airbnb / BYMA" },
  ABNBD: { nombre: "CEDEAR Airbnb Inc. (liq. Dólar MEP)", entidad: "Airbnb / BYMA" },
  ABT: { nombre: "CEDEAR Abbott Laboratories", entidad: "Abbott / BYMA" },
  ABTC: { nombre: "CEDEAR Abbott Laboratories (liq. Cable)", entidad: "Abbott / BYMA" },
  ABTD: { nombre: "CEDEAR Abbott Laboratories (liq. Dólar MEP)", entidad: "Abbott / BYMA" },
  ACN: { nombre: "CEDEAR Accenture plc", entidad: "Accenture / BYMA" },
  ACNC: { nombre: "CEDEAR Accenture plc (liq. Cable)", entidad: "Accenture / BYMA" },
  ACND: { nombre: "CEDEAR Accenture plc (liq. Dólar MEP)", entidad: "Accenture / BYMA" },
  ADBE: { nombre: "CEDEAR Adobe Inc.", entidad: "Adobe / BYMA" },
  ADBEC: { nombre: "CEDEAR Adobe Inc. (liq. Cable)", entidad: "Adobe / BYMA" },
  ADBED: { nombre: "CEDEAR Adobe Inc. (liq. Dólar MEP)", entidad: "Adobe / BYMA" },
  ADI: { nombre: "CEDEAR Analog Devices Inc.", entidad: "Analog Devices / BYMA" },
  ADID: { nombre: "CEDEAR Analog Devices Inc. (liq. Dólar MEP)", entidad: "Analog Devices / BYMA" },
  ADP: { nombre: "CEDEAR Automatic Data Processing", entidad: "ADP / BYMA" },
  ADPD: { nombre: "CEDEAR Automatic Data Processing (liq. Dólar MEP)", entidad: "ADP / BYMA" },
  AEM: { nombre: "CEDEAR Agnico Eagle Mines", entidad: "Agnico Eagle / BYMA" },
  AEMD: { nombre: "CEDEAR Agnico Eagle Mines (liq. Dólar MEP)", entidad: "Agnico Eagle / BYMA" },
  AI: { nombre: "CEDEAR C3.ai Inc.", entidad: "C3.ai / BYMA" },
  AID: { nombre: "CEDEAR C3.ai Inc. (liq. Dólar MEP)", entidad: "C3.ai / BYMA" },
  AIG: { nombre: "CEDEAR American International Group", entidad: "AIG / BYMA" },
  AIGC: { nombre: "CEDEAR American International Group (liq. Cable)", entidad: "AIG / BYMA" },
  AIGD: { nombre: "CEDEAR American International Group (liq. Dólar MEP)", entidad: "AIG / BYMA" },
  AMAT: { nombre: "CEDEAR Applied Materials", entidad: "Applied Materials / BYMA" },
  AMATC: { nombre: "CEDEAR Applied Materials (liq. Cable)", entidad: "Applied Materials / BYMA" },
  AMATD: { nombre: "CEDEAR Applied Materials (liq. Dólar MEP)", entidad: "Applied Materials / BYMA" },
  AMD: { nombre: "CEDEAR Advanced Micro Devices", entidad: "AMD / BYMA" },
  AMDC: { nombre: "CEDEAR Advanced Micro Devices (liq. Cable)", entidad: "AMD / BYMA" },
  AMDD: { nombre: "CEDEAR Advanced Micro Devices (liq. Dólar MEP)", entidad: "AMD / BYMA" },
  AMGN: { nombre: "CEDEAR Amgen Inc.", entidad: "Amgen / BYMA" },
  AMGNC: { nombre: "CEDEAR Amgen Inc. (liq. Cable)", entidad: "Amgen / BYMA" },
  AMGND: { nombre: "CEDEAR Amgen Inc. (liq. Dólar MEP)", entidad: "Amgen / BYMA" },
  AMX: { nombre: "CEDEAR América Móvil", entidad: "América Móvil / BYMA" },
  AMXD: { nombre: "CEDEAR América Móvil (liq. Dólar MEP)", entidad: "América Móvil / BYMA" },
  ANET: { nombre: "CEDEAR Arista Networks", entidad: "Arista Networks / BYMA" },
  ANETC: { nombre: "CEDEAR Arista Networks (liq. Cable)", entidad: "Arista Networks / BYMA" },
  ANETD: { nombre: "CEDEAR Arista Networks (liq. Dólar MEP)", entidad: "Arista Networks / BYMA" },
  ANF: { nombre: "CEDEAR Abercrombie & Fitch", entidad: "Abercrombie & Fitch / BYMA" },
  ANFD: { nombre: "CEDEAR Abercrombie & Fitch (liq. Dólar MEP)", entidad: "Abercrombie & Fitch / BYMA" },
  ARM: { nombre: "CEDEAR Arm Holdings", entidad: "Arm / BYMA" },
  ARMD: { nombre: "CEDEAR Arm Holdings (liq. Dólar MEP)", entidad: "Arm / BYMA" },
  ASML: { nombre: "CEDEAR ASML Holding", entidad: "ASML / BYMA" },
  ASMLC: { nombre: "CEDEAR ASML Holding (liq. Cable)", entidad: "ASML / BYMA" },
  ASMLD: { nombre: "CEDEAR ASML Holding (liq. Dólar MEP)", entidad: "ASML / BYMA" },
  ASTS: { nombre: "CEDEAR AST SpaceMobile", entidad: "AST SpaceMobile / BYMA" },
  ASTSC: { nombre: "CEDEAR AST SpaceMobile (liq. Cable)", entidad: "AST SpaceMobile / BYMA" },
  ASTSD: { nombre: "CEDEAR AST SpaceMobile (liq. Dólar MEP)", entidad: "AST SpaceMobile / BYMA" },
  AVGO: { nombre: "CEDEAR Broadcom Inc.", entidad: "Broadcom / BYMA" },
  AVGOC: { nombre: "CEDEAR Broadcom Inc. (liq. Cable)", entidad: "Broadcom / BYMA" },
  AVGOD: { nombre: "CEDEAR Broadcom Inc. (liq. Dólar MEP)", entidad: "Broadcom / BYMA" },
  AXP: { nombre: "CEDEAR American Express", entidad: "American Express / BYMA" },
  AXPC: { nombre: "CEDEAR American Express (liq. Cable)", entidad: "American Express / BYMA" },
  AXPD: { nombre: "CEDEAR American Express (liq. Dólar MEP)", entidad: "American Express / BYMA" },
  AZN: { nombre: "CEDEAR AstraZeneca plc", entidad: "AstraZeneca / BYMA" },
  AZNC: { nombre: "CEDEAR AstraZeneca plc (liq. Cable)", entidad: "AstraZeneca / BYMA" },
  AZND: { nombre: "CEDEAR AstraZeneca plc (liq. Dólar MEP)", entidad: "AstraZeneca / BYMA" },
  BA: { nombre: "CEDEAR Boeing Company", entidad: "Boeing / BYMA" },
  BABA: { nombre: "CEDEAR Alibaba Group", entidad: "Alibaba / BYMA" },
  BABAC: { nombre: "CEDEAR Alibaba Group (liq. Cable)", entidad: "Alibaba / BYMA" },
  BABAD: { nombre: "CEDEAR Alibaba Group (liq. Dólar MEP)", entidad: "Alibaba / BYMA" },
  BAC: { nombre: "CEDEAR Bank of America", entidad: "Bank of America / BYMA" },
  BAD: { nombre: "CEDEAR Bank of America (liq. Dólar MEP)", entidad: "Bank of America / BYMA" },
  BB: { nombre: "CEDEAR BlackBerry Limited", entidad: "BlackBerry / BYMA" },
  BBD: { nombre: "CEDEAR Banco Bradesco", entidad: "Banco Bradesco / BYMA" },
  BBDC: { nombre: "CEDEAR Banco Bradesco (liq. Cable)", entidad: "Banco Bradesco / BYMA" },
  BBDD: { nombre: "CEDEAR Banco Bradesco (liq. Dólar MEP)", entidad: "Banco Bradesco / BYMA" },
  BHP: { nombre: "CEDEAR BHP Group", entidad: "BHP / BYMA" },
  BHPD: { nombre: "CEDEAR BHP Group (liq. Dólar MEP)", entidad: "BHP / BYMA" },
  BIDU: { nombre: "CEDEAR Baidu Inc.", entidad: "Baidu / BYMA" },
  BIDUC: { nombre: "CEDEAR Baidu Inc. (liq. Cable)", entidad: "Baidu / BYMA" },
  BIDUD: { nombre: "CEDEAR Baidu Inc. (liq. Dólar MEP)", entidad: "Baidu / BYMA" },
  BIIB: { nombre: "CEDEAR Biogen Inc.", entidad: "Biogen / BYMA" },
  BIIBD: { nombre: "CEDEAR Biogen Inc. (liq. Dólar MEP)", entidad: "Biogen / BYMA" },
  BKNG: { nombre: "CEDEAR Booking Holdings", entidad: "Booking Holdings / BYMA" },
  BKNGC: { nombre: "CEDEAR Booking Holdings (liq. Cable)", entidad: "Booking Holdings / BYMA" },
  BKNGD: { nombre: "CEDEAR Booking Holdings (liq. Dólar MEP)", entidad: "Booking Holdings / BYMA" },
  BKR: { nombre: "CEDEAR Baker Hughes", entidad: "Baker Hughes / BYMA" },
  BKRD: { nombre: "CEDEAR Baker Hughes (liq. Dólar MEP)", entidad: "Baker Hughes / BYMA" },
  BMY: { nombre: "CEDEAR Bristol-Myers Squibb", entidad: "Bristol-Myers Squibb / BYMA" },
  BMYC: { nombre: "CEDEAR Bristol-Myers Squibb (liq. Cable)", entidad: "Bristol-Myers Squibb / BYMA" },
  BMYD: { nombre: "CEDEAR Bristol-Myers Squibb (liq. Dólar MEP)", entidad: "Bristol-Myers Squibb / BYMA" },
  BP: { nombre: "CEDEAR BP plc", entidad: "BP / BYMA" },
  BX: { nombre: "CEDEAR Blackstone Inc.", entidad: "Blackstone / BYMA" },
  BXD: { nombre: "CEDEAR Blackstone Inc. (liq. Dólar MEP)", entidad: "Blackstone / BYMA" },
  C: { nombre: "CEDEAR Citigroup Inc.", entidad: "Citigroup / BYMA" },
  CAT: { nombre: "CEDEAR Caterpillar Inc.", entidad: "Caterpillar / BYMA" },
  CATC: { nombre: "CEDEAR Caterpillar Inc. (liq. Cable)", entidad: "Caterpillar / BYMA" },
  CATD: { nombre: "CEDEAR Caterpillar Inc. (liq. Dólar MEP)", entidad: "Caterpillar / BYMA" },
  CCJ: { nombre: "CEDEAR Cameco Corporation", entidad: "Cameco / BYMA" },
  CCJC: { nombre: "CEDEAR Cameco Corporation (liq. Cable)", entidad: "Cameco / BYMA" },
  CCJD: { nombre: "CEDEAR Cameco Corporation (liq. Dólar MEP)", entidad: "Cameco / BYMA" },
  CCL: { nombre: "CEDEAR Carnival Corporation", entidad: "Carnival / BYMA" },
  CCLC: { nombre: "CEDEAR Carnival Corporation (liq. Cable)", entidad: "Carnival / BYMA" },
  CCLD: { nombre: "CEDEAR Carnival Corporation (liq. Dólar MEP)", entidad: "Carnival / BYMA" },
  CL: { nombre: "CEDEAR Colgate-Palmolive", entidad: "Colgate-Palmolive / BYMA" },
  CLD: { nombre: "CEDEAR Colgate-Palmolive (liq. Dólar MEP)", entidad: "Colgate-Palmolive / BYMA" },
  COIN: { nombre: "CEDEAR Coinbase Global", entidad: "Coinbase / BYMA" },
  COINC: { nombre: "CEDEAR Coinbase Global (liq. Cable)", entidad: "Coinbase / BYMA" },
  COIND: { nombre: "CEDEAR Coinbase Global (liq. Dólar MEP)", entidad: "Coinbase / BYMA" },
  COP: { nombre: "CEDEAR ConocoPhillips", entidad: "ConocoPhillips / BYMA" },
  COPD: { nombre: "CEDEAR ConocoPhillips (liq. Dólar MEP)", entidad: "ConocoPhillips / BYMA" },
  COST: { nombre: "CEDEAR Costco Wholesale", entidad: "Costco / BYMA" },
  COSTC: { nombre: "CEDEAR Costco Wholesale (liq. Cable)", entidad: "Costco / BYMA" },
  COSTD: { nombre: "CEDEAR Costco Wholesale (liq. Dólar MEP)", entidad: "Costco / BYMA" },
  CRM: { nombre: "CEDEAR Salesforce Inc.", entidad: "Salesforce / BYMA" },
  CRMC: { nombre: "CEDEAR Salesforce Inc. (liq. Cable)", entidad: "Salesforce / BYMA" },
  CRMD: { nombre: "CEDEAR Salesforce Inc. (liq. Dólar MEP)", entidad: "Salesforce / BYMA" },
  CRWD: { nombre: "CEDEAR CrowdStrike Holdings", entidad: "CrowdStrike / BYMA" },
  CRWDD: { nombre: "CEDEAR CrowdStrike Holdings (liq. Dólar MEP)", entidad: "CrowdStrike / BYMA" },
  CRWV: { nombre: "CEDEAR CoreWeave Inc.", entidad: "CoreWeave / BYMA" },
  CRWVD: { nombre: "CEDEAR CoreWeave Inc. (liq. Dólar MEP)", entidad: "CoreWeave / BYMA" },
  CSCO: { nombre: "CEDEAR Cisco Systems", entidad: "Cisco / BYMA" },
  CSCOC: { nombre: "CEDEAR Cisco Systems (liq. Cable)", entidad: "Cisco / BYMA" },
  CSCOD: { nombre: "CEDEAR Cisco Systems (liq. Dólar MEP)", entidad: "Cisco / BYMA" },
  CVS: { nombre: "CEDEAR CVS Health Corporation", entidad: "CVS Health / BYMA" },
  CVSD: { nombre: "CEDEAR CVS Health Corporation (liq. Dólar MEP)", entidad: "CVS Health / BYMA" },
  CVX: { nombre: "CEDEAR Chevron Corporation", entidad: "Chevron / BYMA" },
  CVXC: { nombre: "CEDEAR Chevron Corporation (liq. Cable)", entidad: "Chevron / BYMA" },
  CVXD: { nombre: "CEDEAR Chevron Corporation (liq. Dólar MEP)", entidad: "Chevron / BYMA" },
  DAL: { nombre: "CEDEAR Delta Air Lines", entidad: "Delta Air Lines / BYMA" },
  DALD: { nombre: "CEDEAR Delta Air Lines (liq. Dólar MEP)", entidad: "Delta Air Lines / BYMA" },
  DD: { nombre: "CEDEAR DuPont de Nemours", entidad: "DuPont / BYMA" },
  DE: { nombre: "CEDEAR Deere & Company", entidad: "Deere & Co / BYMA" },
  DEC: { nombre: "CEDEAR Deere & Company (liq. Cable)", entidad: "Deere & Co / BYMA" },
  DED: { nombre: "CEDEAR Deere & Company (liq. Dólar MEP)", entidad: "Deere & Co / BYMA" },
  DECK: { nombre: "CEDEAR Deckers Brands", entidad: "Deckers Brands / BYMA" },
  DECKC: { nombre: "CEDEAR Deckers Brands (liq. Cable)", entidad: "Deckers Brands / BYMA" },
  DECKD: { nombre: "CEDEAR Deckers Brands (liq. Dólar MEP)", entidad: "Deckers Brands / BYMA" },
  DELL: { nombre: "CEDEAR Dell Technologies", entidad: "Dell / BYMA" },
  DELLD: { nombre: "CEDEAR Dell Technologies (liq. Dólar MEP)", entidad: "Dell / BYMA" },
  DEO: { nombre: "CEDEAR Diageo plc", entidad: "Diageo / BYMA" },
  DEOD: { nombre: "CEDEAR Diageo plc (liq. Dólar MEP)", entidad: "Diageo / BYMA" },
  DHR: { nombre: "CEDEAR Danaher Corporation", entidad: "Danaher / BYMA" },
  DHRC: { nombre: "CEDEAR Danaher Corporation (liq. Cable)", entidad: "Danaher / BYMA" },
  DHRD: { nombre: "CEDEAR Danaher Corporation (liq. Dólar MEP)", entidad: "Danaher / BYMA" },
  DISN: { nombre: "CEDEAR The Walt Disney Company", entidad: "Disney / BYMA" },
  DISNC: { nombre: "CEDEAR The Walt Disney Company (liq. Cable)", entidad: "Disney / BYMA" },
  DISND: { nombre: "CEDEAR The Walt Disney Company (liq. Dólar MEP)", entidad: "Disney / BYMA" },
  DOCU: { nombre: "CEDEAR DocuSign Inc.", entidad: "DocuSign / BYMA" },
  DOCUC: { nombre: "CEDEAR DocuSign Inc. (liq. Cable)", entidad: "DocuSign / BYMA" },
  DOCUD: { nombre: "CEDEAR DocuSign Inc. (liq. Dólar MEP)", entidad: "DocuSign / BYMA" },
  DOW: { nombre: "CEDEAR Dow Inc.", entidad: "Dow / BYMA" },
  DOWC: { nombre: "CEDEAR Dow Inc. (liq. Cable)", entidad: "Dow / BYMA" },
  DOWD: { nombre: "CEDEAR Dow Inc. (liq. Dólar MEP)", entidad: "Dow / BYMA" },
  EBAY: { nombre: "CEDEAR eBay Inc.", entidad: "eBay / BYMA" },
  EBAYC: { nombre: "CEDEAR eBay Inc. (liq. Cable)", entidad: "eBay / BYMA" },
  EBAYD: { nombre: "CEDEAR eBay Inc. (liq. Dólar MEP)", entidad: "eBay / BYMA" },
  ETSY: { nombre: "CEDEAR Etsy Inc.", entidad: "Etsy / BYMA" },
  ETSYC: { nombre: "CEDEAR Etsy Inc. (liq. Cable)", entidad: "Etsy / BYMA" },
  ETSYD: { nombre: "CEDEAR Etsy Inc. (liq. Dólar MEP)", entidad: "Etsy / BYMA" },
  F: { nombre: "CEDEAR Ford Motor Company", entidad: "Ford / BYMA" },
  FCX: { nombre: "CEDEAR Freeport-McMoRan", entidad: "Freeport-McMoRan / BYMA" },
  FCXC: { nombre: "CEDEAR Freeport-McMoRan (liq. Cable)", entidad: "Freeport-McMoRan / BYMA" },
  FCXD: { nombre: "CEDEAR Freeport-McMoRan (liq. Dólar MEP)", entidad: "Freeport-McMoRan / BYMA" },
  FDX: { nombre: "CEDEAR FedEx Corporation", entidad: "FedEx / BYMA" },
  FDXC: { nombre: "CEDEAR FedEx Corporation (liq. Cable)", entidad: "FedEx / BYMA" },
  FDXD: { nombre: "CEDEAR FedEx Corporation (liq. Dólar MEP)", entidad: "FedEx / BYMA" },
  FSLR: { nombre: "CEDEAR First Solar Inc.", entidad: "First Solar / BYMA" },
  FSLRC: { nombre: "CEDEAR First Solar Inc. (liq. Cable)", entidad: "First Solar / BYMA" },
  FSLRD: { nombre: "CEDEAR First Solar Inc. (liq. Dólar MEP)", entidad: "First Solar / BYMA" },
  GE: { nombre: "CEDEAR General Electric", entidad: "General Electric / BYMA" },
  GEC: { nombre: "CEDEAR General Electric (liq. Cable)", entidad: "General Electric / BYMA" },
  GED: { nombre: "CEDEAR General Electric (liq. Dólar MEP)", entidad: "General Electric / BYMA" },
  GEV: { nombre: "CEDEAR GE Vernova Inc.", entidad: "GE Vernova / BYMA" },
  GEVD: { nombre: "CEDEAR GE Vernova Inc. (liq. Dólar MEP)", entidad: "GE Vernova / BYMA" },
  GILD: { nombre: "CEDEAR Gilead Sciences", entidad: "Gilead Sciences / BYMA" },
  GILDC: { nombre: "CEDEAR Gilead Sciences (liq. Cable)", entidad: "Gilead Sciences / BYMA" },
  GILDD: { nombre: "CEDEAR Gilead Sciences (liq. Dólar MEP)", entidad: "Gilead Sciences / BYMA" },
  GLW: { nombre: "CEDEAR Corning Inc.", entidad: "Corning / BYMA" },
  GLWD: { nombre: "CEDEAR Corning Inc. (liq. Dólar MEP)", entidad: "Corning / BYMA" },
  GM: { nombre: "CEDEAR General Motors", entidad: "General Motors / BYMA" },
  GMC: { nombre: "CEDEAR General Motors (liq. Cable)", entidad: "General Motors / BYMA" },
  GMD: { nombre: "CEDEAR General Motors (liq. Dólar MEP)", entidad: "General Motors / BYMA" },
  GOGLC: { nombre: "CEDEAR Golden Ocean Group (liq. Cable)", entidad: "Golden Ocean Group / BYMA" },
  GOGLD: { nombre: "CEDEAR Golden Ocean Group (liq. Dólar MEP)", entidad: "Golden Ocean Group / BYMA" },
  GRMN: { nombre: "CEDEAR Garmin Ltd.", entidad: "Garmin / BYMA" },
  GRMND: { nombre: "CEDEAR Garmin Ltd. (liq. Dólar MEP)", entidad: "Garmin / BYMA" },
  GS: { nombre: "CEDEAR Goldman Sachs", entidad: "Goldman Sachs / BYMA" },
  GSC: { nombre: "CEDEAR Goldman Sachs (liq. Cable)", entidad: "Goldman Sachs / BYMA" },
  GSD: { nombre: "CEDEAR Goldman Sachs (liq. Dólar MEP)", entidad: "Goldman Sachs / BYMA" },
  GSK: { nombre: "CEDEAR GSK plc", entidad: "GSK / BYMA" },
  GSKC: { nombre: "CEDEAR GSK plc (liq. Cable)", entidad: "GSK / BYMA" },
  GSKD: { nombre: "CEDEAR GSK plc (liq. Dólar MEP)", entidad: "GSK / BYMA" },
  GT: { nombre: "CEDEAR Goodyear Tire & Rubber", entidad: "Goodyear / BYMA" },
  GTC: { nombre: "CEDEAR Goodyear Tire & Rubber (liq. Cable)", entidad: "Goodyear / BYMA" },
  GTD: { nombre: "CEDEAR Goodyear Tire & Rubber (liq. Dólar MEP)", entidad: "Goodyear / BYMA" },
  HAL: { nombre: "CEDEAR Halliburton Company", entidad: "Halliburton / BYMA" },
  HALC: { nombre: "CEDEAR Halliburton Company (liq. Cable)", entidad: "Halliburton / BYMA" },
  HALD: { nombre: "CEDEAR Halliburton Company (liq. Dólar MEP)", entidad: "Halliburton / BYMA" },
  HD: { nombre: "CEDEAR The Home Depot", entidad: "Home Depot / BYMA" },
  HDC: { nombre: "CEDEAR The Home Depot (liq. Cable)", entidad: "Home Depot / BYMA" },
  HDD: { nombre: "CEDEAR The Home Depot (liq. Dólar MEP)", entidad: "Home Depot / BYMA" },
  HDB: { nombre: "CEDEAR HDFC Bank Limited", entidad: "HDFC Bank / BYMA" },
  HIMS: { nombre: "CEDEAR Hims & Hers Health", entidad: "Hims & Hers / BYMA" },
  HIMSC: { nombre: "CEDEAR Hims & Hers Health (liq. Cable)", entidad: "Hims & Hers / BYMA" },
  HIMSD: { nombre: "CEDEAR Hims & Hers Health (liq. Dólar MEP)", entidad: "Hims & Hers / BYMA" },
  HL: { nombre: "CEDEAR Hecla Mining", entidad: "Hecla Mining / BYMA" },
  HLD: { nombre: "CEDEAR Hecla Mining (liq. Dólar MEP)", entidad: "Hecla Mining / BYMA" },
  HMC: { nombre: "CEDEAR Honda Motor Co.", entidad: "Honda / BYMA" },
  HMY: { nombre: "CEDEAR Harmony Gold Mining", entidad: "Harmony Gold / BYMA" },
  HMYC: { nombre: "CEDEAR Harmony Gold Mining (liq. Cable)", entidad: "Harmony Gold / BYMA" },
  HMYD: { nombre: "CEDEAR Harmony Gold Mining (liq. Dólar MEP)", entidad: "Harmony Gold / BYMA" },
  HON: { nombre: "CEDEAR Honeywell International", entidad: "Honeywell / BYMA" },
  HOND: { nombre: "CEDEAR Honeywell International (liq. Dólar MEP)", entidad: "Honeywell / BYMA" },
  HOOD: { nombre: "CEDEAR Robinhood Markets", entidad: "Robinhood / BYMA" },
  HOODC: { nombre: "CEDEAR Robinhood Markets (liq. Cable)", entidad: "Robinhood / BYMA" },
  HOODD: { nombre: "CEDEAR Robinhood Markets (liq. Dólar MEP)", entidad: "Robinhood / BYMA" },
  HPQ: { nombre: "CEDEAR HP Inc.", entidad: "HP Inc. / BYMA" },
  HPQC: { nombre: "CEDEAR HP Inc. (liq. Cable)", entidad: "HP Inc. / BYMA" },
  HPQD: { nombre: "CEDEAR HP Inc. (liq. Dólar MEP)", entidad: "HP Inc. / BYMA" },
  HSBC: { nombre: "CEDEAR HSBC Holdings", entidad: "HSBC / BYMA" },
  HSY: { nombre: "CEDEAR The Hershey Company", entidad: "Hershey / BYMA" },
  HSYC: { nombre: "CEDEAR The Hershey Company (liq. Cable)", entidad: "Hershey / BYMA" },
  HSYD: { nombre: "CEDEAR The Hershey Company (liq. Dólar MEP)", entidad: "Hershey / BYMA" },
  HUT: { nombre: "CEDEAR Hut 8 Mining Corp.", entidad: "Hut 8 / BYMA" },
  HUTC: { nombre: "CEDEAR Hut 8 Mining Corp. (liq. Cable)", entidad: "Hut 8 / BYMA" },
  HUTD: { nombre: "CEDEAR Hut 8 Mining Corp. (liq. Dólar MEP)", entidad: "Hut 8 / BYMA" },
  HWM: { nombre: "CEDEAR Howmet Aerospace", entidad: "Howmet Aerospace / BYMA" },
  HWMC: { nombre: "CEDEAR Howmet Aerospace (liq. Cable)", entidad: "Howmet Aerospace / BYMA" },
  HWMD: { nombre: "CEDEAR Howmet Aerospace (liq. Dólar MEP)", entidad: "Howmet Aerospace / BYMA" },
  IBKR: { nombre: "CEDEAR Interactive Brokers Group", entidad: "Interactive Brokers / BYMA" },
  IBKRD: { nombre: "CEDEAR Interactive Brokers Group (liq. Dólar MEP)", entidad: "Interactive Brokers / BYMA" },
  IBM: { nombre: "CEDEAR International Business Machines", entidad: "IBM / BYMA" },
  IBMC: { nombre: "CEDEAR International Business Machines (liq. Cable)", entidad: "IBM / BYMA" },
  IBMD: { nombre: "CEDEAR International Business Machines (liq. Dólar MEP)", entidad: "IBM / BYMA" },
  IBN: { nombre: "CEDEAR ICICI Bank Limited", entidad: "ICICI Bank / BYMA" },
  JD: { nombre: "CEDEAR JD.com Inc.", entidad: "JD.com / BYMA" },
  JNJ: { nombre: "CEDEAR Johnson & Johnson", entidad: "Johnson & Johnson / BYMA" },
  JPM: { nombre: "CEDEAR JPMorgan Chase & Co.", entidad: "JPMorgan Chase / BYMA" },
  MA: { nombre: "CEDEAR Mastercard Incorporated", entidad: "Mastercard / BYMA" },
  MCD: { nombre: "CEDEAR McDonald's Corporation", entidad: "McDonald's / BYMA" },
  MMM: { nombre: "CEDEAR 3M Company", entidad: "3M / BYMA" },
  MO: { nombre: "CEDEAR Altria Group", entidad: "Altria / BYMA" },
  MRK: { nombre: "CEDEAR Merck & Co.", entidad: "Merck / BYMA" },
  MU: { nombre: "CEDEAR Micron Technology", entidad: "Micron / BYMA" },
  NFLX: { nombre: "CEDEAR Netflix Inc.", entidad: "Netflix / BYMA" },
  NKE: { nombre: "CEDEAR Nike Inc.", entidad: "Nike / BYMA" },
  ORCL: { nombre: "CEDEAR Oracle Corporation", entidad: "Oracle / BYMA" },
  PBR: { nombre: "CEDEAR Petróleo Brasileiro (Petrobras)", entidad: "Petrobras / BYMA" },
  PEP: { nombre: "CEDEAR PepsiCo Inc.", entidad: "PepsiCo / BYMA" },
  PFE: { nombre: "CEDEAR Pfizer Inc.", entidad: "Pfizer / BYMA" },
  PG: { nombre: "CEDEAR Procter & Gamble", entidad: "Procter & Gamble / BYMA" },
  PYPL: { nombre: "CEDEAR PayPal Holdings", entidad: "PayPal / BYMA" },
  QCOM: { nombre: "CEDEAR Qualcomm Incorporated", entidad: "Qualcomm / BYMA" },
  SBUX: { nombre: "CEDEAR Starbucks Corporation", entidad: "Starbucks / BYMA" },
  T: { nombre: "CEDEAR AT&T Inc.", entidad: "AT&T / BYMA" },
  TSM: { nombre: "CEDEAR Taiwan Semiconductor (TSMC)", entidad: "TSMC / BYMA" },
  TXN: { nombre: "CEDEAR Texas Instruments", entidad: "Texas Instruments / BYMA" },
  UNH: { nombre: "CEDEAR UnitedHealth Group", entidad: "UnitedHealth / BYMA" },
  UPS: { nombre: "CEDEAR United Parcel Service", entidad: "UPS / BYMA" },
  V: { nombre: "CEDEAR Visa Inc.", entidad: "Visa / BYMA" },
  VALE: { nombre: "CEDEAR Vale S.A.", entidad: "Vale / BYMA" },
  VZ: { nombre: "CEDEAR Verizon Communications", entidad: "Verizon / BYMA" },
  WFC: { nombre: "CEDEAR Wells Fargo & Company", entidad: "Wells Fargo / BYMA" },
  WMT: { nombre: "CEDEAR Walmart Inc.", entidad: "Walmart / BYMA" },
  X: { nombre: "CEDEAR United States Steel", entidad: "US Steel / BYMA" },
  XOM: { nombre: "CEDEAR Exxon Mobil Corporation", entidad: "ExxonMobil / BYMA" },

  // ===== Acciones locales (Merval / BYMA) =====
  GGAL: { nombre: "Grupo Financiero Galicia S.A.", entidad: "BYMA / Merval" },
  GGALD: { nombre: "Grupo Financiero Galicia S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  YPFD: { nombre: "YPF S.A. Clase D", entidad: "BYMA / Merval" },
  YPFDD: { nombre: "YPF S.A. Clase D (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  PAMP: { nombre: "Pampa Energía S.A.", entidad: "BYMA / Merval" },
  PAMPD: { nombre: "Pampa Energía S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  BMA: { nombre: "Banco Macro S.A.", entidad: "BYMA / Merval" },
  "BMA.D": { nombre: "Banco Macro S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  BBAR: { nombre: "BBVA Argentina S.A. (Banco Francés)", entidad: "BYMA / Merval" },
  BBARD: { nombre: "BBVA Argentina S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  BHIP: { nombre: "Banco Hipotecario S.A.", entidad: "BYMA / Merval" },
  BPAT: { nombre: "Banco Patagonia S.A.", entidad: "BYMA / Merval" },
  SUPV: { nombre: "Grupo Financiero Supervielle S.A.", entidad: "BYMA / Merval" },
  SUPVD: { nombre: "Grupo Financiero Supervielle S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  TXAR: { nombre: "Ternium Argentina S.A.", entidad: "BYMA / Merval" },
  TXARD: { nombre: "Ternium Argentina S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  ALUA: { nombre: "Aluar Aluminio Argentino S.A.I.C.", entidad: "BYMA / Merval" },
  ALUAD: { nombre: "Aluar Aluminio Argentino S.A.I.C. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  CRES: { nombre: "Cresud S.A.C.I.F. y A.", entidad: "BYMA / Merval" },
  CRESD: { nombre: "Cresud S.A.C.I.F. y A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  CEPU: { nombre: "Central Puerto S.A.", entidad: "BYMA / Merval" },
  CEPUD: { nombre: "Central Puerto S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  TGSU2: { nombre: "Transportadora de Gas del Sur S.A.", entidad: "BYMA / Merval" },
  TGSUD: { nombre: "Transportadora de Gas del Sur S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  TGNO4: { nombre: "Transportadora de Gas del Norte S.A.", entidad: "BYMA / Merval" },
  TGN4D: { nombre: "Transportadora de Gas del Norte S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  EDN: { nombre: "Empresa Distribuidora y Comercializadora Norte (Edenor)", entidad: "BYMA / Merval" },
  EDND: { nombre: "Edenor S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  IRSA: { nombre: "IRSA Inversiones y Representaciones S.A.", entidad: "BYMA / Merval" },
  IRSAD: { nombre: "IRSA Inversiones y Representaciones S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  LOMA: { nombre: "Loma Negra Cía. Industrial Argentina", entidad: "BYMA / Merval" },
  LOMAD: { nombre: "Loma Negra Cía. Industrial Argentina (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  TRAN: { nombre: "Transener S.A.", entidad: "BYMA / Merval" },
  TRAND: { nombre: "Transener S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  METR: { nombre: "MetroGAS S.A.", entidad: "BYMA / Merval" },
  METRD: { nombre: "MetroGAS S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  TECO2: { nombre: "Telecom Argentina S.A.", entidad: "BYMA / Merval" },
  TECOD: { nombre: "Telecom Argentina S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  VALO: { nombre: "Grupo Financiero Valores S.A.", entidad: "BYMA / Merval" },
  VALOD: { nombre: "Grupo Financiero Valores S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  CVH: { nombre: "Cablevisión Holding S.A.", entidad: "BYMA / Merval" },
  CVHD: { nombre: "Cablevisión Holding S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  BYMA: { nombre: "Bolsas y Mercados Argentinos S.A.", entidad: "BYMA / Merval" },
  BYMAD: { nombre: "Bolsas y Mercados Argentinos S.A. (liq. Dólar MEP)", entidad: "BYMA / Merval" },
  MOLI: { nombre: "Molinos Río de la Plata S.A.", entidad: "BYMA / Merval" },
  AGRO: { nombre: "Agrometal S.A.I.C.", entidad: "BYMA / Merval" },
  AUSO: { nombre: "Autopistas del Sol S.A.", entidad: "BYMA / Merval" },
  CAPX: { nombre: "Capex S.A.", entidad: "BYMA / Merval" },
  MIRG: { nombre: "Mirgor S.A.C.I.F.I.A.", entidad: "BYMA / Merval" },
  LEDE: { nombre: "Ledesma S.A.A.I.", entidad: "BYMA / Merval" },
  MORI: { nombre: "Morixe Hermanos S.A.", entidad: "BYMA / Merval" },
  SAMI: { nombre: "S.A. San Miguel A.G.I.C.I. y F.", entidad: "BYMA / Merval" },
  RICH: { nombre: "Laboratorios Richmond S.A.C.I.F.", entidad: "BYMA / Merval" },
  CGPA2: { nombre: "Camuzzi Gas Pampeana S.A.", entidad: "BYMA / Merval" },
  DGCU2: { nombre: "Distribuidora de Gas Cuyana S.A.", entidad: "BYMA / Merval" },
  GBAN: { nombre: "Gas Natural Ban S.A.", entidad: "BYMA / Merval" },
  INVJ: { nombre: "Inversora Juramento S.A.", entidad: "BYMA / Merval" },
  LONG: { nombre: "Longvie S.A.", entidad: "BYMA / Merval" },
  CELU: { nombre: "Celulosa Argentina S.A.", entidad: "BYMA / Merval" },
  GCLA: { nombre: "Celulosa Argentina S.A. (Clase B)", entidad: "BYMA / Merval" },
  HAVA: { nombre: "Havanna Holding S.A.", entidad: "BYMA / Merval" },
  GRIM: { nombre: "Grimoldi S.A.", entidad: "BYMA / Merval" },
  BOLT: { nombre: "Boldt S.A.", entidad: "BYMA / Merval" },
  MOLA: { nombre: "Molinos Agro S.A.", entidad: "BYMA / Merval" },

  // ===== Bonos soberanos / subsoberanos =====
  AL30: { nombre: "Bono de la Rep. Argentina 2030 (AL30, ley Arg.)", entidad: "Tesoro Nacional / BYMA" },
  GD30: { nombre: "Bono Global Rep. Argentina 2030 (GD30, ley NY)", entidad: "Tesoro Nacional / BYMA" },
  AL35: { nombre: "Bono de la Rep. Argentina 2035 (AL35, ley Arg.)", entidad: "Tesoro Nacional / BYMA" },
  GD35: { nombre: "Bono Global Rep. Argentina 2035 (GD35, ley NY)", entidad: "Tesoro Nacional / BYMA" },
  AE38: { nombre: "Bono de la Rep. Argentina 2038 (AE38)", entidad: "Tesoro Nacional / BYMA" },
  GD38: { nombre: "Bono Global Rep. Argentina 2038 (GD38, ley NY)", entidad: "Tesoro Nacional / BYMA" },
  AL29: { nombre: "Bono de la Rep. Argentina 2029 (AL29, ley Arg.)", entidad: "Tesoro Nacional / BYMA" },
  GD29: { nombre: "Bono Global Rep. Argentina 2029 (GD29, ley NY)", entidad: "Tesoro Nacional / BYMA" },
  AL41: { nombre: "Bono de la Rep. Argentina 2041 (AL41, ley Arg.)", entidad: "Tesoro Nacional / BYMA" },
  GD41: { nombre: "Bono Global Rep. Argentina 2041 (GD41, ley NY)", entidad: "Tesoro Nacional / BYMA" },
  T2X5: { nombre: "Bono del Tesoro en Pesos Cero Cupón (T2X5)", entidad: "Tesoro Nacional / BYMA" },

};

// ===== Mercado EE.UU. (listado directo en NYSE/Nasdaq, no CEDEAR) =====
// data912 expone miles de tickers de EE.UU. (incluyendo microcaps ilíquidos
// que casi nadie busca), lo que hacía la categoría "EE.UU." enorme y lenta
// de renderizar. Se muestra una lista acotada de ETFs indexados de
// referencia (S&P 500, Nasdaq, mercado total) y acciones ampliamente
// reconocidas, en línea con el objetivo original de la sección
// (benchmark tipo S&P 500), en vez de todo el universo de EE.UU.
export const USA_DIRECT_NAMES: Record<string, { nombre: string; entidad: string }> = {
  VOO: { nombre: "Vanguard S&P 500 ETF", entidad: "Vanguard / NYSE Arca" },
  IVV: { nombre: "iShares Core S&P 500 ETF", entidad: "BlackRock / NYSE Arca" },
  SPY: { nombre: "SPDR S&P 500 ETF Trust", entidad: "State Street / NYSE Arca" },
  VTI: { nombre: "Vanguard Total Stock Market ETF", entidad: "Vanguard / NYSE Arca" },
  QQQ: { nombre: "Invesco QQQ Trust (Nasdaq 100)", entidad: "Invesco / Nasdaq" },
  DIA: { nombre: "SPDR Dow Jones Industrial Average ETF", entidad: "State Street / NYSE Arca" },
  AAPL: { nombre: "Apple Inc.", entidad: "Apple / Nasdaq" },
  MSFT: { nombre: "Microsoft Corporation", entidad: "Microsoft / Nasdaq" },
  GOOGL: { nombre: "Alphabet Inc. Clase A (Google)", entidad: "Alphabet / Nasdaq" },
  AMZN: { nombre: "Amazon.com Inc.", entidad: "Amazon / Nasdaq" },
  NVDA: { nombre: "NVIDIA Corporation", entidad: "NVIDIA / Nasdaq" },
  META: { nombre: "Meta Platforms Inc.", entidad: "Meta / Nasdaq" },
  TSLA: { nombre: "Tesla Inc.", entidad: "Tesla / Nasdaq" },
  BRKB: { nombre: "Berkshire Hathaway Inc. Clase B", entidad: "Berkshire Hathaway / NYSE" },
  JPM: { nombre: "JPMorgan Chase & Co.", entidad: "JPMorgan Chase / NYSE" },
  JNJ: { nombre: "Johnson & Johnson", entidad: "Johnson & Johnson / NYSE" },
  V: { nombre: "Visa Inc.", entidad: "Visa / NYSE" },
  MA: { nombre: "Mastercard Incorporated", entidad: "Mastercard / NYSE" },
  WMT: { nombre: "Walmart Inc.", entidad: "Walmart / NYSE" },
  PG: { nombre: "Procter & Gamble", entidad: "Procter & Gamble / NYSE" },
  HD: { nombre: "The Home Depot", entidad: "Home Depot / NYSE" },
  KO: { nombre: "The Coca-Cola Company", entidad: "Coca-Cola / NYSE" },
  PEP: { nombre: "PepsiCo Inc.", entidad: "PepsiCo / Nasdaq" },
  DIS: { nombre: "The Walt Disney Company", entidad: "Disney / NYSE" },
  NFLX: { nombre: "Netflix Inc.", entidad: "Netflix / Nasdaq" },
  ADBE: { nombre: "Adobe Inc.", entidad: "Adobe / Nasdaq" },
  CRM: { nombre: "Salesforce Inc.", entidad: "Salesforce / NYSE" },
  ORCL: { nombre: "Oracle Corporation", entidad: "Oracle / NYSE" },
  INTC: { nombre: "Intel Corporation", entidad: "Intel / Nasdaq" },
  CSCO: { nombre: "Cisco Systems", entidad: "Cisco / Nasdaq" },
  PFE: { nombre: "Pfizer Inc.", entidad: "Pfizer / NYSE" },
  ABBV: { nombre: "AbbVie Inc.", entidad: "AbbVie / NYSE" },
  MRK: { nombre: "Merck & Co.", entidad: "Merck / NYSE" },
  XOM: { nombre: "Exxon Mobil Corporation", entidad: "ExxonMobil / NYSE" },
  CVX: { nombre: "Chevron Corporation", entidad: "Chevron / NYSE" },
  BAC: { nombre: "Bank of America", entidad: "Bank of America / NYSE" },
  WFC: { nombre: "Wells Fargo & Company", entidad: "Wells Fargo / NYSE" },
  GS: { nombre: "Goldman Sachs", entidad: "Goldman Sachs / NYSE" },
  MCD: { nombre: "McDonald's Corporation", entidad: "McDonald's / NYSE" },
  NKE: { nombre: "Nike Inc.", entidad: "Nike / NYSE" },
  SBUX: { nombre: "Starbucks Corporation", entidad: "Starbucks / Nasdaq" },
  QCOM: { nombre: "Qualcomm Incorporated", entidad: "Qualcomm / Nasdaq" },
  TXN: { nombre: "Texas Instruments", entidad: "Texas Instruments / Nasdaq" },
  AMD: { nombre: "Advanced Micro Devices", entidad: "AMD / Nasdaq" },
  BA: { nombre: "Boeing Company", entidad: "Boeing / NYSE" },
  UNH: { nombre: "UnitedHealth Group", entidad: "UnitedHealth / NYSE" },
  T: { nombre: "AT&T Inc.", entidad: "AT&T / NYSE" },
  VZ: { nombre: "Verizon Communications", entidad: "Verizon / NYSE" },
  PYPL: { nombre: "PayPal Holdings", entidad: "PayPal / Nasdaq" },
  UPS: { nombre: "United Parcel Service", entidad: "UPS / NYSE" },

  // Ampliación (antes ~48 tickers, ahora ~95) para que "EE.UU." muestre
  // muchas más alternativas sin perder el criterio original de la lista:
  // ETFs indexados de referencia y acciones ampliamente reconocidas, no
  // microcaps ilíquidas. Ver USA_DIRECT_ALLOWED más abajo.
  MELI: { nombre: "MercadoLibre Inc.", entidad: "MercadoLibre / Nasdaq" },
  COIN: { nombre: "Coinbase Global Inc.", entidad: "Coinbase / Nasdaq" },
  HOOD: { nombre: "Robinhood Markets Inc.", entidad: "Robinhood / Nasdaq" },
  AVGO: { nombre: "Broadcom Inc.", entidad: "Broadcom / Nasdaq" },
  AMAT: { nombre: "Applied Materials Inc.", entidad: "Applied Materials / Nasdaq" },
  MU: { nombre: "Micron Technology Inc.", entidad: "Micron / Nasdaq" },
  ADI: { nombre: "Analog Devices Inc.", entidad: "Analog Devices / Nasdaq" },
  ARM: { nombre: "Arm Holdings plc", entidad: "Arm / Nasdaq" },
  ASML: { nombre: "ASML Holding N.V.", entidad: "ASML / Nasdaq" },
  TSM: { nombre: "Taiwan Semiconductor Manufacturing (TSMC)", entidad: "TSMC / NYSE" },
  IBM: { nombre: "International Business Machines Corp.", entidad: "IBM / NYSE" },
  ABNB: { nombre: "Airbnb Inc.", entidad: "Airbnb / Nasdaq" },
  BKNG: { nombre: "Booking Holdings Inc.", entidad: "Booking Holdings / Nasdaq" },
  CRWD: { nombre: "CrowdStrike Holdings Inc.", entidad: "CrowdStrike / Nasdaq" },
  GILD: { nombre: "Gilead Sciences Inc.", entidad: "Gilead Sciences / Nasdaq" },
  AMGN: { nombre: "Amgen Inc.", entidad: "Amgen / Nasdaq" },
  BMY: { nombre: "Bristol-Myers Squibb Co.", entidad: "Bristol-Myers Squibb / NYSE" },
  CVS: { nombre: "CVS Health Corporation", entidad: "CVS Health / NYSE" },
  CAT: { nombre: "Caterpillar Inc.", entidad: "Caterpillar / NYSE" },
  DE: { nombre: "Deere & Company", entidad: "Deere & Co / NYSE" },
  HON: { nombre: "Honeywell International Inc.", entidad: "Honeywell / Nasdaq" },
  GE: { nombre: "General Electric Company", entidad: "General Electric / NYSE" },
  FDX: { nombre: "FedEx Corporation", entidad: "FedEx / NYSE" },
  DAL: { nombre: "Delta Air Lines Inc.", entidad: "Delta Air Lines / NYSE" },
  AAL: { nombre: "American Airlines Group Inc.", entidad: "American Airlines / Nasdaq" },
  MMM: { nombre: "3M Company", entidad: "3M / NYSE" },
  CL: { nombre: "Colgate-Palmolive Company", entidad: "Colgate-Palmolive / NYSE" },
  MO: { nombre: "Altria Group Inc.", entidad: "Altria / NYSE" },
  COST: { nombre: "Costco Wholesale Corporation", entidad: "Costco / Nasdaq" },
  DECK: { nombre: "Deckers Brands", entidad: "Deckers Brands / NYSE" },
  ETSY: { nombre: "Etsy Inc.", entidad: "Etsy / Nasdaq" },
  EBAY: { nombre: "eBay Inc.", entidad: "eBay / Nasdaq" },
  F: { nombre: "Ford Motor Company", entidad: "Ford / NYSE" },
  GM: { nombre: "General Motors Company", entidad: "General Motors / NYSE" },
  CCL: { nombre: "Carnival Corporation", entidad: "Carnival / NYSE" },
  HPQ: { nombre: "HP Inc.", entidad: "HP Inc. / NYSE" },
  DELL: { nombre: "Dell Technologies Inc.", entidad: "Dell / NYSE" },
  FSLR: { nombre: "First Solar Inc.", entidad: "First Solar / Nasdaq" },
  COP: { nombre: "ConocoPhillips", entidad: "ConocoPhillips / NYSE" },
  HAL: { nombre: "Halliburton Company", entidad: "Halliburton / NYSE" },
  BKR: { nombre: "Baker Hughes Company", entidad: "Baker Hughes / Nasdaq" },
  JD: { nombre: "JD.com Inc.", entidad: "JD.com / Nasdaq" },
  BABA: { nombre: "Alibaba Group Holding Ltd.", entidad: "Alibaba / NYSE" },
  BIDU: { nombre: "Baidu Inc.", entidad: "Baidu / Nasdaq" },
  DOCU: { nombre: "DocuSign Inc.", entidad: "DocuSign / Nasdaq" },
  ANET: { nombre: "Arista Networks Inc.", entidad: "Arista Networks / NYSE" },
  HIMS: { nombre: "Hims & Hers Health Inc.", entidad: "Hims & Hers / NYSE" },
};

export const USA_DIRECT_ALLOWED = new Set(Object.keys(USA_DIRECT_NAMES));


export const fetchData912 = async <T = any>(endpoint: string): Promise<T> => {
  const url = endpoint.startsWith("http") ? endpoint : `${BASE_URL}${endpoint.startsWith("/") ? "" : "/"}${endpoint}`;
  const res = await fetch(url, {
    headers: {
      Accept: "application/json",
    },
  });

  if (!res.ok) {
    throw new Error(`Data912 API error: ${res.status} ${res.statusText}`);
  }

  return res.json() as Promise<T>;
};

export const getLiveCedears = async (): Promise<Data912QuoteRaw[]> => {
  return fetchData912<Data912QuoteRaw[]>("/live/arg_cedears");
};

export const getLiveArgStocks = async (): Promise<Data912QuoteRaw[]> => {
  return fetchData912<Data912QuoteRaw[]>("/live/arg_stocks");
};

export const getLiveArgBonds = async (): Promise<Data912QuoteRaw[]> => {
  return fetchData912<Data912QuoteRaw[]>("/live/arg_bonds");
};

export const getLiveUsaStocks = async (): Promise<Data912QuoteRaw[]> => {
  return fetchData912<Data912QuoteRaw[]>("/live/usa_stocks");
};

// --- Histórico oficial (BYMA vía data912) ---
export interface Data912HistoricalRaw {
  date: string;
  o?: number | null;
  h?: number | null;
  l?: number | null;
  c: number | null;
  v?: number | null;
}

export const getHistoricalCedear = async (ticker: string): Promise<Data912HistoricalRaw[]> => {
  return fetchData912<Data912HistoricalRaw[]>(`/historical/cedears/${ticker}`);
};

export const getHistoricalArgStock = async (ticker: string): Promise<Data912HistoricalRaw[]> => {
  return fetchData912<Data912HistoricalRaw[]>(`/historical/stocks/${ticker}`);
};

export const getHistoricalArgBond = async (ticker: string): Promise<Data912HistoricalRaw[]> => {
  return fetchData912<Data912HistoricalRaw[]>(`/historical/bonds/${ticker}`);
};

